//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by windirstat.rc
//
#define IDD_ABOUTBOX                    100
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_windirstatTYPE              129
#define IDS_QUERYING                    129
#define IDS_NOTACCESSIBLE               130
#define IDB_NODES                       131
#define IDS_TREECOL_ATTRIBUTES          131
#define IDD_SELECTDRIVES                133
#define IDR_POPUPLIST                   134
#define IDB_IMAGELIST                   135
#define IDR_POPUPGRAPH                  136
#define IDR_LICENSE                     137
#define IDD_DELETE_WARNING              138
#define IDD_INVISIBLE                   140
#define IDD_MODALSHELLAPI               140
#define IDD_MODALAPISHUTTLE             140
#define IDD_PAGE_CLEANUPS               141
#define IDD_PAGE_TREELIST               142
#define IDD_PAGE_TREEMAP                143
#define IDD_PAGE_GENERAL                144
#define IDD_REPORTBUG                   145
#define IDD_PAGE_REPORT                 146
#define IDS_RESOURCEVERSION             199
#define IDS_ABOUT_ABOUTTEXTss           200
#define IDS_ABOUT_THANKSTOTEXT          201
#define IDS_ABOUT_ABOUT                 202
#define IDS_ABOUT_THANKSTO              203
#define IDS_ABOUT_LICENSEAGREEMENT      204
#define IDS_MYCOMPUTER                  205
#define IDS_UDC_CONFIRMATIONss          206
#define IDS_RUDC_CONFIRMATIONss         207
#define IDS_THEDIRECTORYsDOESNOTEXIST   208
#define IDS_THEFILEsDOESNOTEXIST        209
#define IDS_COULDNOTCREATEPROCESSssss   210
#define IDS_TREECOL_NAME                211
#define IDS_TREECOL_SUBTREEPERCENTAGE   212
#define IDS_TREECOL_PERCENTAGE          213
#define IDS_TREECOL_SIZE                214
#define IDS_TREECOL_ITEMS               215
#define IDS_TREECOL_FILES               216
#define IDS_TREECOL_SUBDIRS             217
#define IDS_TREECOL_LASTCHANGE          218
#define IDS_PLEASECHECKYOURDISKUSAGE    219
#define IDS_DISKUSAGEREPORTGENERATEDBYWINDIRSTAT 220
#define IDS__UNKNOWN_                   221
#define IDS_FREESPACE_ITEM              222
#define IDS_UNKNOWN_ITEM                223
#define IDS_FILES_ITEM                  224
#define IDS_ONEREADJOB                  225
#define IDS_sREADJOBS                   226
#define IDS_CANNOTOPENCLIPBOARD         227
#define IDS_CANNOTEMTPYCLIPBOARD        228
#define IDS_CANNOTSETCLIPBAORDDATA      229
#define IDS_WINDIRSTAT_SETTINGS         230
#define IDS_SCANNING_                   231
#define IDS_EMPTYRECYCLEBIN             232
#define IDS__ONEITEMss                  233
#define IDS__sITEMSss                   234
#define IDS_UDCsCTRLd                   235
#define IDS_USERDEFINEDCLEANUP0         236
#define IDS_REPORT_DISKUSAGE            237
#define IDS_USERDEFINEDCLEANUPd         238
#define IDS_POLICY_NOREFRESH            239
#define IDS_POLICY_REFRESHTHISENTRY     240
#define IDS_POLICY_REFRESHPARENT        241
#define IDS_BUGREPORTHINT               242
#define IDS_FEEDBACKHINT                243
#define IDS_FROMsPLATFORMs              244
#define IDS_SEV_CRITICAL                245
#define IDS_SEV_GRAVE                   246
#define IDS_SEV_NORMAL                  247
#define IDS_SEV_WISH                    248
#define IDS_SEV_FEEDBACK                249
#define IDS_DRIVECOL_NAME               250
#define IDS_DRIVECOL_TOTAL              251
#define IDS_DRIVECOL_FREE               252
#define IDS_DRIVECOL_GRAPH              253
#define IDS_DRIVECOL_PERCENTUSED        254
#define IDS_SELECTFOLDER                255
#define IDS_EXTCOL_EXTENSION            256
#define IDS_EXTCOL_COLOR                257
#define IDS_EXTCOL_BYTES                258
#define IDS_EXTCOL_FILES                259
#define IDS_EXTCOL_DESCRIPTION          260
#define IDS_RAMUSAGEs                   261
#define IDS_HELPFILEsCOULDNOTBEFOUND    262
#define IDS_SUSPENDED_                  263
#define IDS_SUSPEND                     264
#define IDS_SPEC_BYTES                  265
#define IDS_SPEC_KB                     266
#define IDS_SPEC_MB                     267
#define IDS_SPEC_GB                     268
#define IDS_SPEC_TB                     269
#define IDS_RESETTO_DEFAULTS            270
#define IDS_BACKTO_USERSETTINGS         271
#define IDS_RESETTODEFAULTS             272
#define IDS_BACKTOUSERSETTINGS          273
#define IDS_COLLAPSE                    274
#define IDS_EXPAND                      275
#define IDS_CREATEPROCESSsFAILEDs       276
#define IDS_LANGUAGERESTARTNOW          277
#define IDS_ABOUT_AUTHORS               278
#define IDS_ABOUT_AUTHORSTEXTs          279
#define IDS_TRANSLATORS                 899
#define IDR_TEXT1                       900
#define IDR_AUTHORS                     900
#define IDR_TEXT2                       901
#define IDB_BITMAP1                     902
#define IDB_JUNCTIONPOINT               902
#define IDC_ALLDRIVES                   1000
#define IDC_GROUPS                      1000
#define IDC_ALLLOCALDRIVES              1000
#define IDC_SOMEDRIVES                  1001
#define IDC_EXTENSIONS                  1001
#define IDC_AFOLDER                     1002
#define IDC_MEMBERS                     1002
#define IDC_FOLDERNAME                  1003
#define IDC_BROWSEFOLDER                1004
#define IDC_DRIVES                      1005
#define IDC_TEXT                        1012
#define IDC_TAB                         1013
#define IDC_CAPTION                     1014
#define IDC_FILENAME                    1016
#define IDC_DONTSHOWAGAIN               1017
#define IDC_FOLLOWMOUNTPOINTS           1020
#define IDC_PACMANANIMATION             1021
#define IDC_FOLLOWJUNCTIONS             1021
#define IDC_ASKFORCONFIRMATION          1022
#define IDC_SHOWTIMESPENT               1022
#define IDC_TREEMAPGRID                 1022
#define IDC_SHOWCONSOLEWINDOW           1023
#define IDC_WAITFORCOMPLETION           1024
#define IDC_TREELISTGRID                1028
#define IDC_SHOWGRID                    1028
#define IDC_HUMANFORMAT                 1029
#define IDC_TREEMAPGRIDCOLOR            1030
#define IDC_SHOWGRID2                   1030
#define IDC_SHOWSTRIPES                 1030
#define IDC_SHOWGRID3                   1031
#define IDC_FULLROWSELECTION            1031
#define IDC_RESET                       1034
#define IDC_LIST                        1036
#define IDC_TITLE                       1037
#define IDC_COMMANDLINE                 1038
#define IDC_WORKSFORFILES               1039
#define IDC_WORKSFORDIRECTORIES         1040
#define IDC_WORKSFORFILESFOLDER         1041
#define IDC_WORKSFORDRIVES              1042
#define IDC_REFRESHPOLICY               1043
#define IDC_HELPBUTTON                  1044
#define IDC_ENABLED                     1045
#define IDC_RECURSEINTOSUBDIRECTORIES   1046
#define IDC_HINTSP                      1047
#define IDC_HINTSN                      1048
#define IDC_UP                          1049
#define IDC_DOWN                        1050
#define IDC_FROM                        1050
#define IDC_TO                          1051
#define IDC_WORKSFORUNCPATHS            1051
#define IDC_CRITICAL                    1052
#define IDC_GRAVE                       1053
#define IDC_NORMAL                      1054
#define IDC_WISH                        1055
#define IDC_INAWORD                     1056
#define IDC_APPLICATION                 1057
#define IDC_FEEDBACK                    1058
#define IDC_PLATFORM                    1059
#define IDC_HINT                        1060
#define IDC_COLORBUTTON0                1100
#define IDC_COLORBUTTON1                1101
#define IDC_COLORBUTTON2                1102
#define IDC_COLORBUTTON3                1103
#define IDC_COLORBUTTON4                1104
#define IDC_COLORBUTTON5                1105
#define IDC_COLORBUTTON6                1106
#define IDC_COLORBUTTON7                1107
#define IDC_SLIDER                      1200
#define IDC_BUTTON8                     1201
#define IDC_TREEMAPHIGHLIGHTCOLOR       1202
#define IDC_COMBO                       1203
#define IDC_STATIC_TO                   1204
#define IDC_STATIC_PLATFORM             1205
#define IDC_STATIC_SEVERITY             1206
#define IDC_STATIC_OKHINT               1207
#define IDC_SIZEGRIPPER                 1208
#define IDC_SCALEFACTOR                 1209
#define IDC_HEIGHT                      1210
#define IDC_CUSHIONSHADING              1211
#define IDC_BRIGHTNESS                  1212
#define IDC_KDIRSTAT                    1213
#define IDC_SEQUOIAVIEW                 1214
#define IDC_PREVIEW                     1215
#define IDC_STATICBRIGHTNESS            1216
#define IDC_STATICCUSHIONSHADING        1217
#define IDC_STATICHEIGHT                1218
#define IDC_STATICSCALEFACTOR           1219
#define IDC_LIGHTSOURCE                 1220
#define IDC_SUBJECT                     1221
#define IDC_PREFIX                      1222
#define IDC_SUFFIX                      1223
#define IDC_CHECK1                      1225
#define IDC_USEWDSLOCALE                1225
#define ID_FILE_OPENURL                 32771
#define ID_FILE_OPENRECENT              32772
#define ID_FILE_REFRESHALL              32773
#define ID_CLEANUP_OPENINEXPLORER       32774
#define ID_CLEANUP_COMPRESS             32776
#define ID_CLEANUP_DELETETRASHFILES     32777
#define ID_Menu                         32781
#define ID_TREEMAP_ZOOMIN               32783
#define ID_TREEMAP_ZOOMOUT              32784
#define ID_TREEMAP_SELECTPARENT         32785
#define ID_TREEMAP_REBUILDTREEMAP       32786
#define ID_TREEMAP_HELPABOUTTREEMAPS    32787
#define ID_REPORT_SENDMAILTOOWNER       32788
#define ID_SETTINGS_SHOWTREEMAP         32789
#define ID_SETTINGS_SHOWTOOLBAR         32790
#define ID_SETTINGS_SHOW                32791
#define ID_VIEW_SHOWTREEMAP             32792
#define ID_SETTINGS_CONFIGUREWINDIRSTAT 32793
#define ID_HELP_REPORTBUG               32796
#define ID_HELP_SENDFEEDBACKMAIL        32797
#define ID_FILE_REFRESHSELECTED         32801
#define ID_FILE_CONTINUEREADINGATMOUNTPOINT 32802
#define ID_CLEANUP_MAKECLEAN            32803
#define ID_FILE_OPENRECENT_0            32806
#define ID_FILE_OPENRECENT_1            32807
#define ID_CLEANUP_OPENINCONSOLE        32808
#define ID_CLEANUP_DELETETOTRASHBIN     32809
#define ID_CLEANUP_DELETE               32810
#define ID_CONFIGURE                    32813
#define ID_HELP_MANUAL                  32814
#define ID_HELP_WHATSTHIS               32815
#define ID_REFRESHALL                   32816
#define ID_REFRESHSELECTED              32817
#define ID_CLEANUP_EMPTYRECYCLEBIN      32818
#define ID_VIEW_SHOWFREESPACE           32819
#define ID_VIEW_SHOWUNKNOWN             32820
#define ID_POPUP                        32826
#define ID_Menu32827                    32827
#define ID_Menu32828                    32828
#define ID_Menu32829                    32829
#define ID_BUTTON32835                  32835
#define ID_BUTTON32837                  32837
#define ID_VIEW_SHOWFILETYPES           32846
#define ID_SENDMAILTOOWNER              32856
#define ID_USERDEFINEDCLEANUP0          32900
#define ID_USERDEFINEDCLEANUP1          32901
#define ID_USERDEFINEDCLEANUP2          32902
#define ID_USERDEFINEDCLEANUP3          32903
#define ID_USERDEFINEDCLEANUP4          32904
#define ID_USERDEFINEDCLEANUP5          32905
#define ID_USERDEFINEDCLEANUP6          32906
#define ID_USERDEFINEDCLEANUP7          32907
#define ID_USERDEFINEDCLEANUP8          32908
#define ID_USERDEFINEDCLEANUP9          32909
#define ID_DUMMY_USERDEFINEDCLEANUP     33005
#define ID_POPUP_CANCEL                 33008
#define ID_TREEMAP_RESELECTCHILD        33011
#define ID_Menu33012                    33012
#define ID_Menu33013                    33013
#define ID_CLEANUP_OPEN                 33015
#define ID_CLEANUP_PROPERTIES           33019
#define ID_BUTTON33021                  33021
#define ID_POPUP_TOGGLE                 33023
#define ID_INDICATOR_MEMORYUSAGE        59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        903
#define _APS_NEXT_COMMAND_VALUE         33024
#define _APS_NEXT_CONTROL_VALUE         1226
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
