.Language=Russian,Russian (Русский)

# Plugin name
plugin.name = <(NAME)>

# Device list menu
device.list.title = Список устройств

# Disk menu
disk.menu.pda = кпк
disk.menu.smartphone = смартфон

# Create file list
create.list.progress.title = Обработка каталогов...
create.list.progress.objects = Файлы: %u; Каталоги: %u; Ошибки: %u
create.list.progress.size = Общий размер данных: %S

# Copy files
copy.files.dlg.title = Копирование файлов
copy.files.dlg.path = &Копировать файлы в:
copy.files.dlg.oo = Когда целевой файл существует:
copy.files.dlg.oo.skip = П&ропускать
copy.files.dlg.oo.overwrite = &Перезаписывать
copy.files.dlg.oo.ask = &Спрашивать
copy.files.dlg.move.files = П&еремещать файлы
copy.files.dlg.copy.shared = Копировать открытые для &записи файлы

copy.files.progress.title = Идет копирование...
move.files.progress.title = Идет перемещение...
move.remote.files.progress.title = Идет перемещение...
copy.files.progress.src = Из:
copy.files.progress.dst = В:
copy.files.progress.size = Обработано %7S из %7S [%3u%%] на скорости %9S
copy.files.progress.file.size = Обработано %7S из %7S [%3u%%] на скорости %9S
copy.files.progress.time = Прошло: %8S  Осталось: %8S  Всего: %8S
move.remote.files.progress.time = Прошло: %8S
copy.files.progress.stats = Файлы: %u(%u/%u); Каталоги: %u; Ошибки: %u
move.remote.files.progress.stats = Файлы: %u; Каталоги: %u

overwrite.dlg.title = Перезапись файла
overwrite.dlg.directory.title = Перезапись каталога
overwrite.dlg.question = Целевой файл уже существует. Заменить?
overwrite.dlg.directory.question = Целевой каталог уже существует. Заменить?
overwrite.dlg.source = Источник:
overwrite.dlg.destination = Цель:
overwrite.dlg.newer = (более новый)
overwrite.dlg.yes = &Да
overwrite.dlg.yes.all = Да для &всех
overwrite.dlg.no = &Нет
overwrite.dlg.no.all = Нет для в&сех

copy.files.stats.title = Копирование завершено
copy.files.stats.errors = Ошибок при копировании: %u
copy.files.stats.files = Скопировано(перезаписано/пропущено) файлов: %u(%u/%u)
copy.files.stats.dirs = Обработано каталогов: %u

# Delete files
delete.files.dlg.title = Удалить файлы
delete.files.dlg.label = Удалить выделенные файлы

delete.files.progress.title = Идет удаление...
delete.files.progress.time = Прошло: %8S  Осталось: %8S  Всего: %8S
delete.files.progress.stats = Файлы: %u; Каталоги: %u; Ошибки: %u

delete.files.stats.title = Удаление завершено
delete.files.stats.errors = Ошибок при удалении: %u
delete.files.stats.files = Удалено файлов: %u
delete.files.stats.dirs = Удалено каталогов: %u

# Create directory
create.dir.dlg.title = Создать каталог
create.dir.dlg.path = &Создать каталог:

# Plugin options
options.dlg.title = Параметры
options.dlg.disk.menu = Добавить в меню &дисков
options.dlg.plugin.menu = Добавить в меню &плагинов
options.dlg.disk.menu.number = &Номер элемента в меню дисков:
options.dlg.hide.copy.dlg = Н&е показывать собственный диалог копирования
options.dlg.save.last.dir = &Сохранять последний открытый каталог
options.dlg.use.file.filters = &Использовать файловые фильтры ActiveSync
options.dlg.access.method = Способ подключения (нужен перезапуск Фара):
options.dlg.rapi = &RAPI
options.dlg.rapi2 = RAPI&2
options.dlg.hide.rom.files = Не п&оказывать файлы в ROM
options.dlg.buffer.size = &Размер буфера:
options.dlg.auto.buf.size = &Автоматический
options.dlg.prefix = Пре&фикс плагина (нужен перезапуск):
options.dlg.save.def.values = Со&хранять опции, указанные в диалогах
options.dlg.def.option.values.title = Значения опций по умолчанию
options.dlg.def.option.values = Допо&лнительно
options.dlg.hot.keys.title = Клавиатурные команды
options.dlg.hot.keys = &Клавиатурные команды
options.dlg.hot.key.execute = &Запуск файла на устройстве:
options.dlg.hot.key.attr = &Смена атрибутов файла:
options.dlg.hot.key.hide.rom.files = &Показ/сокрытие файлов в ROM:
options.dlg.exit.on.dot.dot = &Выход из плагина по ".." в корне
options.dlg.show.free.space = Пока&зывать свободное место в заголовке панели

# Common options
options.ignore.errors = &Игнорировать ошибки
options.show.stats = Показывать статистику по завершении:
options.show.stats.always = &Всегда
options.show.stats.never = &Никогда
options.show.stats.if.error = Когда есть &ошибки

# File attributes
attr.dlg.title = Атрибуты файла
attr.dlg.read.only = &Только для чтения
attr.dlg.sparse = &Разреженный
attr.dlg.archive = &Архивный
attr.dlg.temporary = &Временный
attr.dlg.hidden = &Скрытый
attr.dlg.reparse.point = Св&язь
attr.dlg.system = С&истемный
attr.dlg.in.rom = &Файл в ROM
attr.dlg.compressed = С&жатый
attr.dlg.rom.module = &Модуль в ROM
attr.dlg.encrypted = &Зашифрованный

# System info
sysinfo.device.info = Информация об устройстве
sysinfo.os.version = Версия ОС:
sysinfo.program.memory = Оперативная память
sysinfo.storage.memory = Постоянная память
sysinfo.storage.card = Карта памяти
sysinfo.total = Всего:
sysinfo.free = Свободно:
sysinfo.power = Питание
sysinfo.power.type = Тип:
sysinfo.power.online = электросеть
sysinfo.power.offline = батарея
sysinfo.power.backup = резервная батарея
sysinfo.power.battery.level = Заряд батареи:
sysinfo.power.backup.battery.level = Заряд резервной батареи:

# Run dialog
run.dlg.title = Выполнить
run.dlg.cmd.line = &Командная строка:

# File filters
filter.dlg.title = Файловые фильтры
filter.dlg.select.files = Выберите типы файлов для конвертации:
filter.dlg.to = в

# Generic buttons
button.ok = Продолжить
button.cancel = Отмена
button.retry = &Повтор
button.ignore = &Игнорировать
button.ignore.all = Игнорировать &все

# Size and speed suffixes
suffix.size.b = Б
suffix.size.kb = КБ
suffix.size.mb = МБ
suffix.size.gb = ГБ
suffix.size.tb = ТБ
suffix.speed.b = Б/с
suffix.speed.kb = КБ/с
suffix.speed.mb = МБ/с
suffix.speed.gb = ГБ/с
suffix.speed.tb = ТБ/с

# Error log
log.title = Список ошибок
log.scan.dir = Чтение каталога
log.create.dir = Создание каталога
log.copy.file = Копирование файла
log.delete.file = Удаление файла
log.delete.dir = Удаление каталога
log.show = &Показать ошибки

# Information & progress messages
progress.prepare = Подготовка...
progress.filter = Идёт обработка в файловом фильтре...
progress.interrupt = Прервать текущую операцию?

# Error messages
err.no.activesync = ActiveSync не установлен либо установлена старая версия
err.no.device = Устройство не подключено
err.plugin.init = Невозможно создать экземпляр плагина
err.self.copy = Нельзя копировать файл в самого себя
err.device.disconnected = Устройство было отключено
err.invalid.cmd.line = Командная строка составлена неверно
err.fatal = Неожиданное исключение, вероятно это ошибка в плагине.
err.fatal.dump = Minidump успешно сохранен в каталоге плагина.
err.fatal.no.dump = Установите dbghelp.dll чтобы иметь возможность записать minidump.
err.com.model = Другой плагин уже инициализировал подсистему COM в однопоточном режиме. Это препятствует корректной работе WMDC на Windows Vista. Рекомендуется включить режим RAPI в настройках плагина.
err.not.activesync.user = ActiveSync установлен но не инициализирован для текущего пользователя.
err.same.name.exists = Объект другого типа с таким же именем уже существует.
err.invalid.hot.key = Некорректная комбинация клавиш: '%s'.
err.invalid.prefix = Неверно указан префикс плагина.
